apiVersion: v1
kind: Service
metadata:
  name: fastapi-sentiment-analysis-service
spec:
  selector:
    app: fastapi-sentiment-analysis
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
